
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Install Firefox
      run: sudo apt-get install firefox
    - name: Check clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: wasm-pack test --headless --firefox --verbose
